frontend:
  - frontend/**
  
backend:
  - backend/**
  
model:
  - model/**
  
supabase:
  - supabase/**
  
ci:
  - .github/**
  
docs:
  - "*.md"
  - docs/**
  
dependencies:
  - "package*.json"
  - "requirements*.txt"
  - "pyproject.toml"
  - "poetry.lock"
  - "Pipfile*"
